version: '3'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: Docker/
      dockerfile: backend.Dockerfile
    volumes:
      - backend:/djangoSource
    ports:
      - 8000:8000
    restart: on-failure


volumes:
  backend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend