version: '3'

services:
  backend:
    container_name: backend
    build:
      context: Docker/Backend/
      dockerfile: backend.Dockerfile
    env_file:
      - django.env
    volumes:
      - backend:/djangoSource
    ports:
      - 8000:8000
    depends_on:
      - postgresql
    restart: on-failure

  postgresql:
    container_name: postgresql
    build:
      context: Docker/PostgreSQL
      dockerfile: postgresql.Dockerfile
    env_file:
      - postgres.env
    volumes:
      - postgresql:/usr/local/pgsql/data
    restart: on-failure
    expose:
      - 5432

volumes:
  backend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend
  postgresql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/${USER}/pgdatabase