# Generated by Django 4.2.11 on 2024-03-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_alter_app_user_options_alter_app_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App_user',
        ),
    ]
