# Generated by Django 4.2.11 on 2024-03-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_customuser_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='game_history',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='spa.customuser'),
        ),
    ]
