# Generated by Django 4.2.11 on 2024-03-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_remove_customuser_game_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default='-1', max_length=20, unique=True),
        ),
    ]
