# Generated by Django 4.2.11 on 2024-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0013_customuser_blocklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blocklist',
            field=models.ManyToManyField(blank=True, related_name='user_blocklist', to='spa.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='spa.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='income_friends_requests',
            field=models.ManyToManyField(blank=True, related_name='user_income_friend_requests', to='spa.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='outcome_friends_requests',
            field=models.ManyToManyField(blank=True, related_name='user_outcome_friend_requests', to='spa.customuser'),
        ),
    ]
