# Generated by Django 4.2.11 on 2024-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0014_alter_customuser_blocklist_alter_customuser_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='income_friends_requests',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='outcome_friends_requests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='incoming_friends_requests',
            field=models.ManyToManyField(blank=True, related_name='user_incoming_friend_requests', to='spa.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='outgoing_friends_requests',
            field=models.ManyToManyField(blank=True, related_name='user_outgoing_friend_requests', to='spa.customuser'),
        ),
    ]
