# Generated by Django 4.2.13 on 2024-06-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0017_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ingame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
