# Generated by Django 4.2.8 on 2024-01-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_1", models.CharField(max_length=255)),
                ("player_2", models.CharField(max_length=255)),
                ("mode", models.CharField(max_length=1)),
                ("status", models.CharField(default="En cours", max_length=50)),
                ("score_1", models.IntegerField()),
                ("score_2", models.IntegerField()),
            ],
        ),
    ]
